### ISSUE TITLE
Application for Simplyfied Chinese Translation

### ISSUE THREAD

**Issue by ZeMingoh233** [ykundesu/SuperNewRoles#247]
Hi there. I'm Zeming, an amateur Chinese translator subordinate to For Han sinicization group (You may know me for the translation of TOR-GM,so nice to meet you;) ). Recently we found Super New Roles, and after playing for a period of time many of Chinese fans are fascinated in your mod. As a result, we've managed to translate it into a Chinese version and here I am to ask whether you would like to apply our translation to your mod or not. It's of great honour if you accept our translation.

**Comment by satsumaimoamo** [comment]
Hello.
Nice to meet you.
Thank you for the nice issue.
We did not know that SuperNewRoles is popular in China.
We would like to have your Chinese translation adapted to this mod so that many people can play it.
So we would like to change the current translation system to one using Excel like TORGM as soon as possible.
So please translate using Excel
Thank you very much. 
From Satsuma.

**Comment by ZeMingoh233** [comment]
[transdate.xlsx](https://github.com/ykundesu/SuperNewRoles/files/9075914/transdate.xlsx)
Sorry for my late. Here's our translation. We managed to combine all languages into one tablet by excel (referencing TOR-GM). Hope that meet your expectations.

**Comment by ZeMingoh233** [comment]
Hi it's me again. Well, I recall that during our translation process our art designer redrawed some of the button images and apply them to the game, so I take the liberty of sending her work to you to ask for having a look at them. If you think they're good, we'll not stingy to give them to you and add them in as part of your mod.
[Images.zip](https://github.com/ykundesu/SuperNewRoles/files/9081099/Images.zip)

**Comment by Dekokiyo** [comment]
hello.
My name is DekoKiyo and I am in charge of translation.
Chinese translation will be completed soon.
We are very grateful and would like to include your team name in the game.
What name would you like?

**Comment by Dekokiyo** [comment]
And thank you for taking the trouble to send me the image files!
We'll be happy to install them if we find any that we can use.

**Comment by ZeMingoh233** [comment]
> hello. My name is DekoKiyo and I am in charge of translation. Chinese translation will be completed soon. We are very grateful and would like to include your team name in the game. What name would you like?

Hello Dekokiyo. Thanks for your works!
Our group is called 四个憨批汉化组 in Chinese, and Four Han sinicization group in English. Of course is better to use Chinese, in order to show our copyright of our translation to players in China. 
What's more, our work is in the name of the whole team, so it's no need for adding signature of any single member of us aside our team name.
Lastly, thank you for your approving of our images!
