### ISSUE TITLE
Help! We need Chinese!

### ISSUE THREAD

**Issue by ponyzerteal** [ykundesu/SuperNewRoles#325]
We like your team's mod very much, but suffer from the lack of Chinese. Please update the Chinese version.

**Comment by satsumaimoamo** [comment]
Hello.
I'm working on the Chinese translation right now!
Just give me a minute!
From satsuma

**Comment by Dekokiyo** [comment]
hello
My name is DekoKiyo and I am in charge of embedding Chinese translation.
We are pleased to inform you that the Chinese translation has been completed.
Please wait for a while until the implementation update.
