### ISSUE TITLE
Chinese Translate

### ISSUE THREAD

**Issue by JieGeLovesDengDuaLang** [ykundesu/SuperNewRoles#335]
Hello.
I heard you're adding Chinese translate for SuperNewRoles. I think you guys can not speak/understand Chinese so you'll use machine translate just like google translate, it won't very precise.  I think you guys maybe need human translate, it is precise. i hope it can help you for Translation progress.
I'm only 75% finished for translation, I'm sorry about that.
Finally thank you for your effort in translate.
Github can't upload json files, so I changed file's suffix to txt for upload.
[SuperNewRoles.Resources.translatedate (75% finished).txt](https://github.com/ykundesu/SuperNewRoles/files/9136915/SuperNewRoles.Resources.translatedate.75.finished.txt)

(PS: My English isn't good so I used Google Translate, I hope it can make you understand)

Thank you very much!!!
From JieGe

**Comment by ykundesu** [comment]
Translation into Chinese has been completed.
Also, it does not make sense to fill out the translate.json directly. (It will be overwritten.)
