### ISSUE TITLE
Ask for the next version update time

### ISSUE THREAD

**Issue by MC-AS-Huier** [ykundesu/SuperNewRoles#378]
Roughly when will the next SNR version be updated with support for SChinese

**Comment by Kuki12345** [comment]
In the next update, SNR will support Chinese.  Please wait for the next update.  An update is planned for the summer.

**Comment by MC-AS-Huier** [comment]
But the SChinese translation in the development branch is not perfect

**Comment by Dawn66642** [comment]
We can do it perfectly. i bet! 
:)
