### ISSUE TITLE
ask questions

### ISSUE THREAD

**Issue by MC-AS-Huier** [ykundesu/SuperNewRoles#381]
My friend and I plan to localize the readme file, and I would like to ask if we can do PR after the localization. My friends and I formed an amateur Among us module translation group, called "两个少年汉化组" in English, abbreviated as 2T translation group, whether we can participate in the sinicization of SNR, we will provide long-term support for it, providing SChinese and TChinese translation file.

**Comment by Dawn66642** [comment]
respect bro :))))))
