### ISSUE TITLE
Readmeのミスについて

### ISSUE THREAD

**Issue by kazumaYT** [ykundesu/SuperNewRoles#390]
ReadmeのTheOtherRolesの"Eisbison"さんの名前を"Eisbision"と記載していて、おそらくミスであろうと思い報告させていただきます。

**Comment by soukunsandesu** [comment]
~~プルリクしたれよ()~~

**Comment by Dekokiyo** [comment]
わざわざMod開発大好きな人のためにボタン押すだけで済むようなプルリクではなくIssue送り付けるとこ尊敬します

**Comment by kazumaYT** [comment]
プルリクすりゃよかったわ()

**Comment by soukunsandesu** [comment]
やっぱ開発陣に直してもらおう()

**Comment by Kurato-Tsukishiro** [comment]
英語のReadmeも
.<br>じゃなくて<br>.になっているというおかしいところがあるんですよね・・・

一緒に直しておきます

**Comment by yurinakira** [comment]
PR溜まってるのなんとかしたれよ()
issueの問い合わせも誰か答えてあげてよ()

**Comment by Dekokiyo** [comment]
Issue対応してたK氏が開発者辞めちゃったんでねぇ...

**Comment by jukimaguro1** [comment]
PR溜めが魅力のMod

**Comment by Kurato-Tsukishiro** [comment]
修正がマージされたので閉じていいんですよね　多分
