### ISSUE TITLE
Hi bro :)

### ISSUE THREAD

**Issue by Dekokiyo** [ykundesu/SuperNewRoles#402]
Hi!
Are you remember me?

I found a Translate File! in my computer! Yeah!

Do you want it?
Sure. I'll give you it.

What? "No thank you"!?

Oh my god.
You must more thinking.

Sorry.
Please send your answer.
Bye.

**Comment by soukunsandesu** [comment]
草

**Comment by soukunsandesu** [comment]
やぁ
覚えてる？

ワイのパソコンに翻訳ファイルあったよ！

ほしい？
もちろんあげるよ。

は？要らない？

なんてことだ。
お前らもっと頭使えよ。

ごめん。
回答待ってますはぁと
ばいびー

**Comment by Dekokiyo** [comment]
I understand you are so idiot now.
Bye.
I'll delete Translate File this night.
:)
