### ISSUE TITLE
SNNPハット以外の実装について

### ISSUE THREAD

**Issue by Kurato-Tsukishiro** [ykundesu/SuperNewRoles#459]
- [ ] TORハットを実装している状態は問題がある。

    - SNRはTORのフォークでない。
    - ハット自体のライセンスはGPLではなく、ライセンス無しの為「GPL適応だから使える」というものではない。
    - ハット提供者様に著作権がある(TORハット等に委託されていない)場合、提供者様に個別で許可を取る必要があるがそれができていない。
<br>

- 承認を得ているハットのリポジトリURLが分からない為、私では削除ができない

- 既に使ってしまっていることに対し各リポジトリ所有者に報告(シンプルに・使ってしまっていた事とその謝罪だけを)
    - 提供者様に個別に連絡が必要なようならその連絡を
    
<hr>

### 開発者7号としての意見

　「別Modのハットを実装する」と最初に話が上がった際、開発者3号と7号は「TORHatにライセンスはない」事を提示して、
実装を拒否しておりました。
また、更にマシュマロにおいてかなりきつい意見を投げておりますが、それをスルーして実装なされております。

　**この問題に関してはよっキングさん自身の手で解決してください。**
自分が**理由も出して拒否していた事を強行され**、それにも関わらず問題に対処しなければいけない事に納得がいきません。

　この状況は立派な**ライセンス違反**です。これを放置するような、**開発体制では私と開発者9号も関わりたくありません**。
問題があるのをわかっていてついていくことなどできません。

　早急な対処よろしくお願いいたします。

**Comment by ykundesu** [comment]
明日対処します(時間がないため)

**Comment by soukunsandesu** [comment]
放置すなどつキング()

**Comment by Dekokiyo** [comment]
もうバラしたから正直に謝りに行け
少なくともTORの人は怒ってるからね
